export const EXAMPLE_DUMMY_DATA = [
  {
    name: 'John Doe',
    statusName: 'Active',
    createdDate: new Date().toISOString(),
    total: 12500,
    isSelected: false,
  },
  {
    name: 'Jane Smith',
    statusName: 'Inactive',
    createdDate: new Date().toISOString(),
    total: 12500,
    isSelected: false,
  },
  {
    name: 'Alice Johnson',
    statusName: 'Pending',
    createdDate: new Date().toISOString(),
    total: 12500,
    isSelected: false,
  },
  {
    name: 'Bob Brown',
    statusName: 'Active',
    createdDate: new Date().toISOString(),
    total: 12300,
    isSelected: false,
  },
  {
    name: 'Charlie Davis',
    statusName: 'Inactive',
    createdDate: new Date().toISOString(),
    total: 12200,
    isSelected: false,
  },
  {
    name: 'Diana Evans',
    statusName: 'Active',
    createdDate: new Date().toISOString(),
    total: 12100,
    isSelected: false,
  },
  {
    name: 'Frank Green',
    statusName: 'Pending',
    createdDate: new Date().toISOString(),
    total: 12500,
    isSelected: false,
  },
  {
    name: 'Grace Hall',
    statusName: 'Active',
    createdDate: new Date().toISOString(),
    total: 12500,
    isSelected: false,
  },
  {
    name: 'Henry Irwin',
    statusName: 'Inactive',
    createdDate: new Date().toISOString(),
    total: 12500,
    isSelected: false,
  },
  {
    name: 'Ivy Jenkins',
    statusName: 'Pending',
    createdDate: new Date().toISOString(),
    total: 12500,
    isSelected: false,
  },
  {
    name: 'Henry',
    statusName: 'Inactive',
    createdDate: new Date().toISOString(),
    total: 12500,
    isSelected: false,
  },
  {
    name: 'Ivy',
    statusName: 'Pending',
    createdDate: new Date().toISOString(),
    total: 12500,
    isSelected: false,
  },
];
